src/application/auth/urls.py
#coding: utf-8
from django.conf.urls import include, url

from views import *

urlpatterns = [
    url(r'^$', LoginView.as_view(), name='index'),
    #url(r'^forgot/$', forgot, name='forgot'),
    #url(r'^change/$', change, name='change'),
    url(r'^logout/$', LogoutView.as_view(), name='logout'),
    url(r'^register/$', RegisterView.as_view(), name='register'),
]

src/application/main/urls.py
from django.conf import settings
from django.conf.urls import include, static, url
from django.conf.urls.i18n import i18n_patterns
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.contrib import admin

from sitetree.sitetreeapp import register_i18n_trees

from views import *
from models import *

urlpatterns = []

for page in Page.objects.all():
    urlpatterns += [url(r'^(?P<url>%s)$' % page.url, PageView.as_view())]

urlpatterns += i18n_patterns(
    url(r'^$', IndexView.as_view(), name='index'),
    url(r'^auth/', include('application.auth.urls', app_name='auth', namespace='auth')),
    url(r'^news/', include('application.news.urls', app_name='news', namespace='news')),
    url(r'^blog/', include('application.blog.urls', app_name='blog', namespace='blog')),
    url(r'^admin/', admin.site.urls),
    url(r'^comment/(?P<app_label>\w+)/(?P<model>\w+)/(?P<pk>\d+)/$', CommentList.as_view(), name='comment.list'),
    url(r'^comment/create/$', CommentCreate.as_view(), name='comment.create'),
    url(r'^feedback/', include('application.feedback.urls', app_name='feedback', namespace='feedback')),
    url(r'^summernote/', include('django_summernote.urls')),
) + static.static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) \
+ static.static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

# Now register i18n trees.
register_i18n_trees(['site'])

if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [url(r'^__debug__/', include(debug_toolbar.urls))] + urlpatterns

@receiver(post_save, sender=Page)
def addUrlPatternOnAfterSave(sender, instance, **kwargs):
    global urlpatterns

    urlpatterns += [url(r'^(?P<url>%s)$' % instance.url, PageView.as_view())]

src/application/news/urls.py
#coding: utf-8
from django.conf.urls import url
from views import *

urlpatterns = [
    url(r'^(?P<slug>\w+)/$', NewsList.as_view(), name='index'),
    url(r'^(?P<slug>\w+)/(?P<pk>\d+)/$', NewsDetail.as_view(), name='detail'),
]

src/application/news/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.utils.translation import ugettext_lazy as _

from application.main.models import File

class Category(models.Model):
    title = models.CharField(unique=True, max_length=30, verbose_name=_(u'Наименование'))
    slug = models.SlugField(unique=True, default='', max_length=30, verbose_name=_(u'Символьный код'))

    class Meta:
        verbose_name = _(u'Категория')
        verbose_name_plural = _(u'Категории')
        ordering = ['-title']

    def __unicode__(self):
        return self.title

class Entry(models.Model):
    title = models.CharField(max_length=100,  verbose_name=_(u'Наименование'))
    picture = models.ManyToManyField(File, blank=True, related_name='%(app_label)s_entries', verbose_name=_(u'Изображение'))
    detail_text = models.TextField(verbose_name=_(u'Детальный текст'))
    preview_text = models.TextField(verbose_name=_(u'Текст анонса'))
    category = models.ForeignKey(Category, null=True, related_name='entries', verbose_name=_(u'Категория'))
    date_modify = models.DateTimeField(auto_now=True, editable=False, verbose_name=_(u'Дата изменения'))
    date_create = models.DateTimeField(auto_now_add=True, verbose_name=_(u'Дата создания'))

    class Meta:
        verbose_name = _(u'Запись')
        verbose_name_plural = _(u'Записи')
        ordering = ['-date_create']

    def __unicode__(self):
        return self.title

src/application/news/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.views.generic import ListView, DetailView

from models import *

class NewsList(ListView):
    template_name = 'news/index.html'

    def get_queryset(self):
        if self.kwargs.get('slug'):
            return Entry.objects.filter(category__slug=self.kwargs.get('slug'))

        return Entry.objects.all()

    def get_context_data(self, **kwargs):
        data = super(NewsList, self).get_context_data(**kwargs)

        if self.kwargs.get('slug'):
            data['category'] = Category.objects.get(slug=self.kwargs.get('slug'))

        return data

class NewsDetail(DetailView):
    model = Entry
    template_name = 'news/detail.html'

    def get_context_data(self, **kwargs):
        data = super(NewsDetail, self).get_context_data(**kwargs)

        if data.get('entry') and not data.get('category'):
            data['category'] = data.get('entry').category

        return data

src/application/news/templates/news/detail.html
{% extends 'news.html' %}
{% block title %} {{ object.title }} {% endblock %}
{% block component %}
    <div class="news-detail">
        <div class="news-detail__title">
            {{ object.title|title }}
        </div>
        <div class="news-item__date">
            {{ object.date_create|date:'d M Y H:i' }}
        </div>
        <div class="news-detail__body" data-category="{{ object.category.first.code }}">
             {% if object.picture.exists %}
                <ul class="news-detail__body-picture">
                    {% for picture in object.picture.all %}
                        <li class="news-detail__body-picture_{% cycle 'odd' 'even' %}">
                            <img src="{% resize picture.file.path 100 100 %}" width="100" height="100" />
                        </li>
                    {% endfor %}
                </ul>
             {% endif %}
            <p>{{ object.detail_text|urlize|linebreaks }}</p>
        </div>
    </div>
    {% comment_object entry %}
{% endblock %}

src/application/news/templates/news/index.html
{% extends 'news.html' %}
{% block title %} {% trans 'Новости' %} {% endblock %}
{% block component %}
    <div class="news-list">
        {% for item in object_list %}
            <div class="news-item">
                <div class="news-item__title">
                    <a href="{% url 'news:detail' slug=item.category.slug pk=item.id %}">{{ item.title|title }}</a>
                </div>
                <div class="news-item__date">
                    {% ifchanged %}
                        {{ item.date_create|date:"d M Y" }}
                    {% else %}
                        {% trans 'В тот же день но в ' %}
                    {% endifchanged %}
                    {{ item.date_create|date:"H:i" }}
                </div>
                <div class="news-item__body">
                    <p>{{ item.preview_text|truncatewords:5 }}</p>
                </div>
            </div>
        {% empty %}
            <div class="news-empty">
                {% trans 'Нет новостей!' %}
            </div>
        {% endfor %}
    </div>
{% endblock %}