src/application/auth/urls.py
#coding: utf-8
from django.conf.urls import include, url

from views import *

urlpatterns = [
    url(r'^$', LoginView.as_view(), name='index'),
    #url(r'^forgot/$', forgot, name='forgot'),
    #url(r'^change/$', change, name='change'),
    url(r'^logout/$', LogoutView.as_view(), name='logout'),
    url(r'^register/$', RegisterView.as_view(), name='register'),
]

src/application/blog/urls.py
#coding: utf-8
from django.conf.urls import url

from views import *

urlpatterns = [
    url(r'^$', BlogList.as_view(), name='index'),
    url(r'^create/$', BlogCreate.as_view(), name='create'),
    url(r'^update/$', BlogUpdate.as_view(), name='update'),
    url(r'^(?P<slug>[\w\-]+)/$', BlogDetail.as_view(), name='detail'),
    url(r'^(?P<slug>[\w\-]+)/list/$', EntryList.as_view(), name='entry.list'),
    url(r'^(?P<slug>[\w\-]+)/(?P<pk>\d+)/$', EntryDetail.as_view(), name='entry.detail'),
    url(r'^entry/create/$', EntryCreate.as_view(), name='entry.create'),
    url(r'^entry/update/(?P<pk>\d+)/$', EntryUpdate.as_view(), name='entry.update'),
    url(r'^entry/delete/(?P<pk>\d+)/$', EntryDelete.as_view(), name='entry.delete'),
]

src/application/main/urls.py
from django.conf import settings
from django.conf.urls import include, static, url
from django.conf.urls.i18n import i18n_patterns
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.contrib import admin

from sitetree.sitetreeapp import register_i18n_trees

from views import *
from models import *

urlpatterns = []

for page in Page.objects.all():
    urlpatterns += [url(r'^(?P<url>%s)$' % page.url, PageView.as_view())]

urlpatterns += i18n_patterns(
    url(r'^$', IndexView.as_view(), name='index'),
    url(r'^auth/', include('application.auth.urls', app_name='auth', namespace='auth')),
    url(r'^news/', include('application.news.urls', app_name='news', namespace='news')),
    url(r'^blog/', include('application.blog.urls', app_name='blog', namespace='blog')),
    url(r'^admin/', admin.site.urls),
    url(r'^comment/(?P<app_label>\w+)/(?P<model>\w+)/(?P<pk>\d+)/$', CommentList.as_view(), name='comment.list'),
    url(r'^comment/create/$', CommentCreate.as_view(), name='comment.create'),
    url(r'^feedback/', include('application.feedback.urls', app_name='feedback', namespace='feedback')),
    url(r'^summernote/', include('django_summernote.urls')),
) + static.static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) \
+ static.static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

# Now register i18n trees.
register_i18n_trees(['site'])

if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [url(r'^__debug__/', include(debug_toolbar.urls))] + urlpatterns

@receiver(post_save, sender=Page)
def addUrlPatternOnAfterSave(sender, instance, **kwargs):
    global urlpatterns

    urlpatterns += [url(r'^(?P<url>%s)$' % instance.url, PageView.as_view())]

src/application/blog/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.urls import reverse
from django.utils.translation import ugettext_lazy as _

from application.main.models import User

# Create your models here.
class Blog(models.Model):
    title = models.CharField(max_length=100, verbose_name=_(u'Наименование'))
    slug = models.SlugField(unique=True, max_length=32, verbose_name=_(u'Адресная строка'))
    description = models.TextField(verbose_name=_(u'Описание'))
    author = models.OneToOneField(User, unique=True, verbose_name=_(u'Автор'))
    date_modify = models.DateTimeField(auto_now=True, editable=False, verbose_name=_(u'Дата изменения'))
    date_create = models.DateTimeField(auto_now_add=True, verbose_name=_(u'Дата создания'))

    class Meta:
        verbose_name = _(u'Блог')
        verbose_name_plural = _(u'Блоги')
        ordering = ['-date_create']

    def __unicode__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:detail', kwargs={'slug': self.slug})

class Entry(models.Model):
    title = models.CharField(max_length=100, verbose_name=_(u'Наименование'))
    content = models.TextField(verbose_name=_(u'Содержимое'))
    blog = models.ForeignKey(Blog, related_name='entries', on_delete=models.CASCADE, verbose_name=_(u'Блог'))
    date_modify = models.DateTimeField(auto_now=True, editable=False, verbose_name=_(u'Дата изменения'))
    date_create = models.DateTimeField(auto_now_add=True, verbose_name=_(u'Дата создания'))

    class Meta:
        verbose_name = _(u'Запись')
        verbose_name_plural = _(u'Записи')
        ordering = ['-date_create']

    def __unicode__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:entry.detail', kwargs={'pk': self.pk, 'slug': self.blog.slug})

src/application/blog/forms.py
#coding: utf-8
from django import forms

from application.main.forms import WysiwygForm
from models import *

class BlogForm(forms.ModelForm):
    class Meta:
        model = Blog
        fields = ['title', 'slug', 'description']
        widgets = {'description': WysiwygForm()}

class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['title', 'content']
        widgets = {'content': WysiwygForm(config={'toolbar': [
            ['font', ['bold', 'italic', 'underline', 'strikethrough', 'clear']],
                ['insert', ['link', 'picture', 'video', 'hr']],
                    ['para', ['ul', 'ol', 'paragraph']]]})}

src/application/blog/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import redirect
from django.views.generic import View, ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView

from forms import *
from models import *

# Create your views here.
class BlogMixinView(View):
    def get_object(self, queryset=None):
        return self.model.objects.get(author=self.request.user)

    def get_success_url(self):
        return reverse('blog:detail', kwargs={'slug': self.object.slug})

class EntryMixinView(View):
    def get_success_url(self):
        return reverse('blog:entry.list', kwargs={'slug': self.object.blog.slug})

    def get_context_data(self, **kwargs):
        data = super(EntryMixinView, self).get_context_data(**kwargs)

        if data.get('entry') and not data.get('blog'):
            data['blog'] = data.get('entry').blog

        return data

class EntryModifyMixinView(View):
    def get_queryset(self):
        return self.model.objects.filter(blog__author=self.request.user)

class BlogList(ListView):
    model = Blog
    template_name = 'blog/index.html'

class BlogDetail(DetailView):
    model = Blog
    template_name = 'blog/detail.html'

class BlogCreate(BlogMixinView, CreateView):
    model = Blog
    form_class = BlogForm
    template_name = 'blog/create.html'

    def get(self, request, *args, **kwargs):
        items = self.model.objects.filter(author=request.user)

        if items.exists():
            item = items[0]

            return redirect('blog:detail', slug=item.slug)

        return super(BlogCreate, self).get(request, *args, **kwargs)

    def form_valid(self, form):
        blog = form.save(commit=False)
        blog.author = self.request.user

        return super(BlogCreate, self).form_valid(form)

class BlogUpdate(BlogMixinView, UpdateView):
    model = Blog
    form_class = BlogForm
    template_name = 'blog/update.html'

class BlogDelete(BlogMixinView, DeleteView):
    model = Blog
    form_class = BlogForm
    template_name = 'blog/update.html'

class EntryList(ListView):
    model = Entry
    template_name = 'blog/entry/list.html'
    paginate_by = 5

    def get_queryset(self):
        return Entry.objects.filter(blog__slug=self.kwargs['slug'])

    def get_context_data(self, **kwargs):
        data = super(EntryList, self).get_context_data(**kwargs)
        data['blog'] = Blog.objects.get(slug=self.kwargs['slug'])

        return data

class EntryDetail(EntryMixinView, DetailView):
    model = Entry
    template_name = 'blog/entry/detail.html'

class EntryCreate(EntryMixinView, CreateView):
    model = Entry
    form_class = EntryForm
    template_name = 'blog/entry/create.html'

    def form_valid(self, form):
        entry = form.save(commit=False)
        entry.blog = Blog.objects.get(author=self.request.user)

        return super(EntryCreate, self).form_valid(form)

class EntryUpdate(EntryModifyMixinView, EntryMixinView, UpdateView):
    model = Entry
    form_class = EntryForm
    template_name = 'blog/entry/update.html'

class EntryDelete(EntryModifyMixinView, EntryMixinView, DeleteView):
    model = Entry
    template_name = 'blog/entry/delete.html'

src/application/blog/templates/blog/create.html
{% extends 'blog.html' %}
{% block title %} {% trans 'Создать блог' %} {% endblock %}
{% block component %}
    <form method="POST" action="{% url 'blog:create' %}" name="blog-create"{% if form.is_multipart %}enctype="multipart/form-data"{% endif %}>
		{% csrf_token %}
		{{ form.as_ul }}
		<input class="btn btn-primary" type="submit" value="{% trans 'Создать блог' %}"/>
	</form>
{% endblock %}

src/application/blog/templates/blog/delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

src/application/blog/templates/blog/detail.html
{% extends 'blog.html' %}
{% block title %} {{ object.title|title }} {% endblock %}
{% block component %}
    <div class="blog-detail">
        <div class="blog-detail__title">
            <h2>{{ object.title|title }}</h2>
        </div>
        <div class="blog-detail__description">
            {% wysiwyg object.description %}
        </div>
        {% if request.user == object.author %}
            <div class="blog-detail__action">
                <a class="btn btn-sm btn-success" href="{% url 'blog:entry.create' %}">{% trans 'Создать пост' %}</a>
                <a class="btn btn-sm btn-info" href="{% url 'blog:update' %}">{% trans 'Редактировать блог' %}</a>
            </div>
        {% endif %}
        <div class="post-list">
            {% for item in object.entries.all|slice:":5" %}
                <div class="post-item">
                    <div class="post-item__title">
                        <a href="{% url 'blog:entry.detail' slug=object.slug pk=item.pk %}">{{ item.title|title }}</a>
                    </div>
                    <div class="post-item__date">
                        {% ifchanged %}
                            {{ item.date_create|date:"d M Y" }}
                        {% else %}
                            {% trans 'В тот же день но в ' %}
                        {% endifchanged %}
                        {{ item.date_create|date:"H:i" }}
                    </div>
                    <div class="post-item__content">
                        <p>{{ item.content|striptags|truncatewords:5 }}</p>
                    </div>
                    {% if request.user == item.blog.author %}
                        <div class="post-item__action">
                            <a class="btn btn-sm btn-warning" href="{% url 'blog:entry.update' pk=item.pk %}">{% trans 'Редактировать пост' %}</a>
                        </div>
                    {% endif %}
                </div>
            {% empty %}
                <div class="post-empty">
                    {% trans 'Нет записей у блога!' context 'blog detail' %}
                </div>
            {% endfor %}
        </div>
        {% if object.entries.count > 5 %}
            <a href="{% url 'blog:entry.list' slug=object.slug %}">{% trans 'Показать все записи' %}</a>
        {% endif %}
    </div>
{% endblock %}

src/application/blog/templates/blog/entry.html
{% extends 'blog.html' %}
{% block title %} {% trans 'Запись блога' %} {% endblock %}
{% block component %}

{% endblock %}

src/application/blog/templates/blog/index.html
{% extends 'blog.html' %}
{% block title %} {% trans 'Список блогов' %} {% endblock %}
{% block component %}
    <div class="blog-list">
        {% for item in object_list %}
            <div class="blog-item">
                <div class="blog-item__title">
                    <a href="{% url 'blog:detail' slug=item.slug %}">{{ item.title|title }}</a>
                </div>
                <div class="blog-item__description">
                    <p>{{ item.description|striptags|truncatewords:5 }}</p>
                </div>
            </div>
        {% empty %}
            <div class="blog-empty">
                {% trans 'Нет блогов!' %}
            </div>
        {% endfor %}
    </div>
{% endblock %}

src/application/blog/templates/blog/update.html
{% extends 'blog.html' %}
{% block title %} {% trans 'Редактировать блог' %} {% endblock %}
{% block component %}
    <form method="POST" action="{% url 'blog:update' %}" name="blog-update"{% if form.is_multipart %}enctype="multipart/form-data"{% endif %}>
		{% csrf_token %}
		{{ form.as_ul }}
		<input class="btn btn-primary" type="submit" value="{% trans 'Редактировать блог' %}"/>
	</form>
{% endblock %}